version: "3.8"

services:
  php:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
