services:
  php:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www/html
    command: >
        bash -c "apt-get update && apt-get install -y libpq-dev && 
        docker-php-ext-install pdo pdo_pgsql && 
        php-fpm"
    depends_on:
      - postgresql

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgresql

  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: progetto_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql